For this workshop we'll be using GitHub Codespaces. 

Instructions below for using Codespaces or if you're working locally. 

## On Codespaces

**1. Quarto environment:** Load the Quarto Codespaces container

-   Go to [mcanouil's Quarto Codespaces](https://github.com/mcanouil/quarto-codespaces)
-   Click 'Use this template' and then 'Open in a codespace'
-   Wait for the codespace to load!

**2. Tools:** Install some VS Code extensions.

-   The Quarto extension and Quarto CLI are already installed. You're all set there!
-   Install the Jupyter Extension: <https://marketplace.visualstudio.com/items?itemName=ms-toolsai.jupyter>

**3. Environment:** Set up the environment

-   Go to View -> Command Palette
-   Search for and select `Python: Create Environment...` and choose `Venv`, then choose the (latest) Python version. 
-   Install jupyter. At the terminal type `python3 -m pip install jupyter`


**4. Exercises:** Get the exercises from [`https://github.com/tracykteal/quarto-GT-pyopensci-exercises`](https://github.com/tracykteal/quarto-GT-pyopensci-exercises).

-   Go to the Terminal in your codespace
-   Type `git clone https://github.com/tracykteal/quarto-GT-pyopensci-exercises.git`
-   You'll see the directory `quarto-GT-pyopensci-exercises` appear in your file navigator.
-   Go into that directory.

**5. Packages:** Install some packages. 

Open `setup.qmd` and run the installation code block to install:

  - polars
  - pandas
  - great_tables
  - selenium
  - plotnine
